steps:

  - checkout

  - attach_workspace:
      when:
        condition: <<parameters.workspace>>
      at: <<parameters.workspace>>

  - when:
      condition: <<parameters.before-deploy>>
      steps: <<parameters.before-deploy>>

  - deploy-and-wait:
      stack-name: <<parameters.stack-name>>
      input-json: <<parameters.input-json>>
      template-file: <<parameters.template-file>>

  - when: 
      condition: <<parameters.after-deploy>>
      steps: <<parameters.after-deploy>>

  - save-outputs:
      stack-name: <<parameters.stack-name>>
      output-json: <<parameters.output-json>>

  - list-stack-errors:
      stack-name: <<parameters.stack-name>>

  - persist_to_workspace:
      when:
        condition: <<parameters.workspace>>
      root: <<parameters.workspace>>
      paths:
        - "*.json"