version: 1

update_configs:

  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - davidkelley

  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"